name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/trailers.json'
      - '.github/workflows/crawl.yml'
  workflow_run:
    workflows: [Crawl]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # these permissions are required for the action to work properly
    permissions:
      pages: write
      id-token: write
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run pg_restore
        uses: docker://postgres:14.3
        with:
          entrypoint: psql
          args: -d postgresql://${{ env.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ env.POSTGRES_DB }} -f ./data/data.sql
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build pages
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Export pages
        run: npm run export
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Upload Pages artifact # https://github.com/actions/upload-pages-artifact/blob/main/action.yml
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: ./out/
      - name: Deploy to GitHub Pages # https://github.com/actions/deploy-pages
        id: deployment
        uses: actions/deploy-pages@v4
